stages:
- "test"

.test-template:
  stage: test
  image: python:3.9.6-slim-buster
  tags:
  - docker-runner
  except:
  - tags
  before_script:
  - pip install poetry==1.4.2
  - poetry config virtualenvs.create false
  - poetry install

black:
  extends:
  - .test-template
  script:
  - black --check .

flake8:
  extends:
  - .test-template
  script:
  - flake8 --count .

mypy:
  extends:
  - .test-template
  script:
  - mypy .

pytest:
  extends:
  - .test-template
  services:
  - name: postgres:13.8-bullseye
    alias: database
  variables:

    # Postgresql variables
    RABBIT_BACKEND_DB_HOST: database
    POSTGRES_PASSWORD: rabbit_backend
    POSTGRES_USER: rabbit_backend
    POSTGRES_DB: rabbit_backend
  script:
  - apt update
  - apt install -y wait-for-it
  - wait-for-it -t 180 $RABBIT_BACKEND_DB_HOST:5432
  - pytest -vv --junitxml=report.xml --cov="rabbit_backend" .
  - coverage xml
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
