"""empty message

Revision ID: 919c97dc10ac
Revises: 819cbf6e030b
Create Date: 2024-04-09 15:47:20.697771

"""

# revision identifiers, used by Alembic.
revision = "919c97dc10ac"
down_revision = "819cbf6e030b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
