version: '3.9'
services:
  api:
    image: $IMAGE
    labels:
      kompose.image-pull-secret: gitlab-secret
      kompose.service.expose: $URL
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      ingress.kubernetes.io/ssl-redirect: 'false'
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    ports: [8000]
  db:
    labels:
      kompose.service.healthcheck.readiness.test: sh -c redis-cli ping
    ports: [5432]
  redis:
    ports: [6379]
  migrator:
    image: $IMAGE
